../../tests/invalid/TryCatch_Invalid_1.whiley:19: variable may be uninitialised
        sys.out.println("CAUGHT EXCEPTION: " ++ x)
                                                ^
